### ISSUE TITLE
Bullets and spaces (paragraphs) don't show

### ISSUE THREAD

**Issue by Joannaover** [wonderland-industry/lontaine#4]
![image](https://user-images.githubusercontent.com/48246083/64697553-645ab480-d4a1-11e9-840d-28ba1499dfbb.png)

**Comment by mykimbui** [comment]
done should show in a min

**Comment by Joannaover** [comment]
Paragraphs show - bullet points don't @mykimbui

**Comment by mykimbui** [comment]
doone
